name: kidsworld
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: 
  url_launcher: ^5.4.0
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^2.0.0
  lazy_load_scrollview: ^1.0.1
  video_player: ^0.10.1
  flutter_launcher_icons: ^0.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/kids.ico"

flutter:
  uses-material-design: true
  assets:
    - icon/kids.ico
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.


# The following line ensures that the Material Icons font is
# included with your application, so that you can use the icons in
# the material Icons class.
  

# To add assets to your application, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
assets:
  - image/A.jpg
  - image/b.jpg
  - image/c.png
  - image/d.jpg
  - image/e.png
  - image/f.jpg
  - image/g.jpg
  - image/h.jpg
  - image/i.jpg
  - image/j.jpg
  - image/l.jpg
  - image/m.jpg
  - image/n.jpg
  - image/o.jpg
  - image/p.jfif
  - image/q.jfif
  - image/s.jfif
  - image/t.jpg
  - image/u.jpg
  - image/v.jfif
  - image/w.jfif
  - image/x.png
  - image/y.jfif
  - image/z.jpg
  - ani/camel.jpeg
  - ani/cat.jpeg
  - ani/cheeta.jpeg
  - ani/deer.jpeg
  - ani/dog.jpeg
  - ani/elephant.jpeg
  - ani/giraffe.jpeg
  - ani/horse.jpeg
  - ani/lion.jpeg
  - ani/monkey.jpeg
  - ani/rabbit.jpg
  - ani/shark.jpeg
  - ani/sheep.jpeg
  - ani/squrriel.jpeg
  - ani/tiger.jpeg
  - video/rhymes.mp4
     

     

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages

# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
